### ISSUE TITLE
Failed to launch with forge 1.12.2-14.23.4.2708

### ISSUE THREAD

**Issue by a3626a** [BuiltBrokenModding/MinecraftJUnit#5]
For the first, I appreciate this great work.

Hi. I am author of [Hungry-Animals](https://github.com/a3626a/HungryAnimals). I'm trying to use MinecraftJUnit to unit test my mod. I have watched your [video](https://www.youtube.com/watch?v=uTgYv1NzIMs).

Here's my `build.gradle`
```
buildscript {
    repositories {
        jcenter()
        maven {
            url = "http://files.minecraftforge.net/maven"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

targetCompatibility=8
sourceCompatibility=8

version = "${mc_version}-${mod_version}"
group= "com.oortcloud.hungryanimals"
archivesBaseName = "hungryanimals"

minecraft {
    version = "${mc_version}-14.23.4.2708"
    runDir = "run"
    
	replace "@VERSION@", project.version
    replaceIn "References.java"
	
    mappings = "snapshot_20171003"
}

dependencies {}

processResources
{
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
                
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
        
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

repositories {
    maven { // TOP
        name 'tterrag maven'
        url "http://maven.tterrag.com/"
    }
    maven {
        name = "COFH, Codechicken"
        url "http://maven.covers1624.net/"
    }
    maven {
        // location of the maven that hosts JEI files
        name = "Progwml6 maven"
        url = "http://dvs1.progwml6.com/files/maven"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "modmaven.k-4u.nl"
    }
    maven {
        name="bbm"
        url="http://api.dmodoomsirius.me/"
    }
}

dependencies {
    deobfCompile "mcjty.theoneprobe:TheOneProbe-1.12:1.12-1.4.19-11"
    
    // compile against the JEI API but do not include it at runtime
    deobfProvided "mezz.jei:jei_${mc_version}:${jei_version}:api"
    // at runtime, use the full JEI jar
    runtime "mezz.jei:jei_${mc_version}:${jei_version}"
    
    // JUnit
    compile 'com.google.jimfs:jimfs:1.1'
    compile "junit:junit:4.11"
    compile "com.builtbroken.minecraftjunit:MinecraftJUnit:1.12.2-0.+:deobf"
}
```

Here's my `AbstractTest` class. Actually, this class does not refer any `MinecraftJUnit` specific tools like `FakeWorld`. I posted this issue for other unit tests.
```
package oortcloud.hungryanimals.configuration;

import java.io.IOException;
import java.nio.file.FileSystem;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.Map;

import org.junit.Test;
import org.junit.runner.RunWith;

import com.builtbroken.mc.testing.junit.AbstractTest;
import com.builtbroken.mc.testing.junit.VoltzTestRunner;
import com.google.common.collect.Lists;
import com.google.common.jimfs.Configuration;
import com.google.common.jimfs.Jimfs;
import com.google.gson.JsonElement;

import oortcloud.hungryanimals.configuration.master.NodeOverride;
import oortcloud.hungryanimals.configuration.master.NodePath;
import oortcloud.hungryanimals.utils.R;

@RunWith(VoltzTestRunner.class)
public class NodeTest extends AbstractTest{

	FileSystem system = null;
	Path directory1 = null;
	Path directory2 = null;
	
	@Override
	public void setUpForEntireClass() {
		system = Jimfs.newFileSystem(Configuration.unix());
		
		try {
			Path root = system.getPath("config", "hungryanimals");
			Files.createDirectories(root);
			
			directory1 = root.resolve("1");
			Files.write(directory1.resolve("a.txt"), Lists.newArrayList(
					"{",
					"\"field1\" : 1,",
					"}"
					), StandardOpenOption.CREATE);
			Files.write(directory1.resolve("b.txt"), Lists.newArrayList(
					"{",
					"\"field1\" : 2,",
					"}"
					), StandardOpenOption.CREATE);
			directory2 = root.resolve("2");
			Files.write(directory2.resolve("a.txt"), Lists.newArrayList(
					"{",
					"\"field1\" : 3",
					"}"
					), StandardOpenOption.CREATE);
		} catch (IOException e) {
			fail("failed to prepare test environment, Jimfs virtual memory file system");
		}
	}
	
	@Test
	public void NodeOverride_Build_Overrideen() {
		Map<R, JsonElement> map1 = new NodeOverride(new NodePath(directory1), new NodePath(directory2)).build();
		assertEquals(1, map1.get(R.get("a.txt")).getAsJsonObject().get("field1").getAsInt());
		assertNull(map1.get(R.get("b.txt")));
		
		Map<R, JsonElement> map2 = new NodeOverride(new NodePath(directory2), new NodePath(directory1)).build();
		assertEquals(3, map2.get(R.get("a.txt")).getAsJsonObject().get("field1").getAsInt());
		assertEquals(2, map2.get(R.get("b.txt")).getAsJsonObject().get("field1").getAsInt());
	}
	
}

```

I got this error while launching my code by clicking **Run-Run As-JUnit Test**
![image](https://user-images.githubusercontent.com/4434752/41847097-d4d8abea-78b3-11e8-9d57-52c3d54b7a3c.png)

```
2018-06-25 19:58:24,274 main WARN Disabling terminal, you're running in an unsupported environment.
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.builtbroken.mc.testing.junit.VoltzTestRunner.init(VoltzTestRunner.java:80)
	at com.builtbroken.mc.testing.junit.VoltzTestRunner.<init>(VoltzTestRunner.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:87)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:73)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:46)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:522)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:291)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:285)
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:40)
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:19)
	at net.minecraft.util.SoundEvent.registerSound(SoundEvent.java:580)
	at net.minecraft.util.SoundEvent.registerSounds(SoundEvent.java:26)
	at net.minecraft.init.Bootstrap.register(Bootstrap.java:570)
	... 23 more
```

Am I missing something? or is it a bug of `MinecraftJUnit`?

**Comment by DarkGuardsman** [comment]
It might be a bug, hard to say as I've not run into it before. I will do more testing but it could be a missing dep or something. Best case I just need to update the lib to the latest forge. Worst case I may need to remake the loader. 

Also, that test class, if it's not using Minecraft code you can use normal JUnit. The Abstract Test and voltz runner are mainly used to solve issues loading block registry and worlds.

**Comment by MaPePeR** [comment]
If i would have to make a guess i would say it has to do with a `@NotNull`-Annotation. But i haven't worked with java for years now, so take that with a grain of salt.

**Comment by a3626a** [comment]
Following minimalized example causes same error.
```
package oortcloud.hungryanimals.configuration;

import org.junit.runner.RunWith;

import com.builtbroken.mc.testing.junit.AbstractTest;
import com.builtbroken.mc.testing.junit.VoltzTestRunner;

@RunWith(VoltzTestRunner.class)
public class MCJUnitTest extends AbstractTest {

}
```
